language: go
go:
- 1.10.1
script:
  - make
before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64
  -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - go get -u golang.org/x/tools/cmd/goimports
  - go get -u golang.org/x/lint/golint
install:
  - dep ensure -vendor-only
before_deploy:
  - ls release/
  - make VERSION=${TRAVIS_TAG} release -j2
deploy:
  provider: releases
  api_key:
    secure: IDtjerJ+t4OF1XDdtOygLCV18qg0L0Trs59FPXL519b17VUDtljGQXEN63uDaC5MD7E0WFbANHLG+1iz8C5D+Mdwjt3ut6PncORzJOWacsFAFAH6Ez8l+5UwCBLljPXeWza8iW0no3DcSaWcqmNzWE7QzvdXM7cFJc1hAEOoIf16aeFgDOQ3ZXLHbtQ8f8j4fABchZ11XbvhemeyWt/9D996apyPTPuyc+eudcP04ZePz3pmKGLpJWoxTxJv2Aw692weckgtgjnIdTbhUas0gq+S3/B+cU+jZ4+WPDFo+zWVOxH5yQ2/b497hYv0UjwtmxPfmd9S6XgnTsPL1vnJy52Ab1QFloQU2/JjoWpUi64wxcktbIBChrnge5QfN+UbEau2ZTPgBCunmfEAntIQ9geIOGoFKFpIPCqfVKxEYsp9mLN6f+VuEbBtRDw5RlU3sp5Th8nu5mVoBLmaYvBkxO+PRpDZHdv1DmwDB3ep7FxUDbNMa7sE7cmbDX47EQ+tkF/Qu/jwlCSNBhTwP39Fc3In8hfmTOXXDH3H4NP+yxTZU9Zi9IvYpNtVCDoX+5y/D2wOfzn7Tv7O1PBpBzCM90reveB+OfjcmK7agioLV6n0HWdGfvAL0c/t5xE2TeZ5/qosRp0xVOvaXwbkrMnnTD3aMZp5CxoKEtHbaU9iwQw=
  file_glob: true
  file: release/*
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
env:
  global:
    - "PATH=$PATH:$HOME/local/bin"
    - DEP_VERSION="0.4.1"
