language: go
go:
- 1.10.1
cache:
  directories:
  - "$HOME/local"
before_install:
- curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64
  -o $GOPATH/bin/dep
- chmod +x $GOPATH/bin/dep
- go get -u golang.org/x/tools/cmd/goimports
- go get -u golang.org/x/lint/golint
install:
- dep ensure -vendor-only
notifications:
  email: false
env:
  global:
  - PATH=$PATH:$HOME/local/bin
  - DEP_VERSION="0.4.1"
deploy:
  provider: releases
  api_key:
    secure: MR2G5BKW5lPIiQjmWYOYYx3kIoYY1X6YvO3yIhlN2D6yWd7ERZlSOVw9K+QPdlpp2SgSY3hCAKjxttwSj56ixAtq3KOjdhFNom/xC2+QRWLozoqiSWruaRinVbtoA6gaea6gqI3JVQUsN45h8DKrpyAl/oFVMbp1UuWjOdBYYtHgdT5hem80k3apMFKs61p5LfTcJtBrrJse/2YPmY4d4sIFfZONJACp1MbYKENWdyLkNb6NfkGK2VuWQSZ7AM47x9s7RKII/hHHb6cuF4pYYMa3xBZxF5cYj+63bzZ+sOWiXZz9QWdXPrC3tel1WoznD60rQSG1ooajxEX2xPVcse0ezZTENx+cVZGpdGHBz7jTpk8W2QHQVjPxktYogezunUbS5lXuK1ovH5nqrZH0RH4ZFXrnJOeCN+9kz0X5Vl7gyPxZIBMi0Igfecfl+jRMHbrAf65f0wV/VxgSn93DOuULRt7PUq2FjQd1EjYIrVjm0zMoh0ZlXnrIISrfu5AzeGuJ+UGzMMr/hFuf+RhsmH+5CGUZIEqGmHaawKbpiJnb2l+QDDdevSWkTAL/ICR9pJUbV586aM1e3zT0eZvPYHI1kZcLSbwwryQXecv0gAM/FgKCB6ofPdOVReiXKQ5t7949RUN+SdZ9KVhpmhBmJVPQVmpgGHnVH9pV/lhqLMI=
  file: "./bin/*"
  on:
    repo: gertd/awsctl
    branch: master
